### ISSUE TITLE
Address in "Tunnel status" does not include "https://" prefix

### ISSUE THREAD

**Issue by derekantrican** [fieldOfView/OctoPrint-ngrok#15]
The address listed in the plugin settings under "Tunnel status" does not include the "https://" prefix. This is a problem because if you simply copy the contents of that box and paste it into a browser you will get the error: `Tunnel [subDomain].ngrok.io not found` (this made me think the plugin wasn't working for a few days before I realized it was because the "https://" was required). If the "https://" was included in that text box this would not be an issue

**Comment by fieldOfView** [comment]
Right next to the address, to the left of the "Close" button, there is a link button. You can click it to visit the tunnel link, or right-click and select Copy link location to get the full tunnel address.

**Comment by derekantrican** [comment]
Good to know - I didn't know you could right click that button. I think my suggestion still stands
