### ISSUE TITLE
0.1.1 Install Loop

### ISSUE THREAD

**Issue by jneilliii** [fieldOfView/OctoPrint-ngrok#2]
you forgot to bump your setup.py version...

**Comment by fieldOfView** [comment]
I did not know I had to do that

**Comment by jneilliii** [comment]
If you don't the installed version is detected incorrectly versus what's in releases and will constantly think there is a new version.

**Comment by fieldOfView** [comment]
0.1.2 it is then: https://github.com/fieldOfView/OctoPrint-ngrok/releases/tag/0.1.2
