### ISSUE TITLE
got 404 Client Error: Not Found for url: https://codeload.github.com/fieldOfView/OctoPrint-ngrok/zip/master

### ISSUE THREAD

**Issue by nifri** [fieldOfView/OctoPrint-ngrok#29]
Trying to install via Octoprint I receive the following error message: 

Installiere Plugin...
Installiere Plugin "Ngrok Tunnel" von https://github.com/fieldOfView/OctoPrint-ngrok/archive/master.zip...
Fehler!
Could not fetch plugin from server, got 404 Client Error: Not Found for url: https://codeload.github.com/fieldOfView/OctoPrint-ngrok/zip/master

Opening https://github.com/fieldOfView/OctoPrint-ngrok/archive/master.zip in browser also returns a 404 error message.

**Comment by fieldOfView** [comment]
Sorry, my fault. I fixed it.

**Comment by nifri** [comment]
Thank you for the quick fix and also thank you for providing this plugin!
