### ISSUE TITLE
[Feature Request] Expose tunnel addresse in settings

### ISSUE THREAD

**Issue by 2BWorks** [fieldOfView/OctoPrint-ngrok#3]
I've checked out your plugin and i would love to integrate it with my plugin. So the user can easily access their octoprint from the app on 3G and 4G. By exposing the address. My plugin could hook into it. Let me know if this is something that has your interest.

(NL hier :) )

**Comment by fieldOfView** [comment]
The tunnel address is not a setting, it is a runtime variable. So I don't think it should be exposed as a setting. You can access the tunnel name via the SimpleApi of the plugin (`api/plugin/ngrok`). Would that work for you?

**Comment by 2BWorks** [comment]
Thanks! That's a great idea
